name: PR Collection Labeler

on: pull_request_target

jobs:
  pr_collection_labeler:
    runs-on: ubuntu-latest
    steps:
    - name: Add collection labels
      if: github.event.action == 'opened'
      uses: ignition-tooling/pr-collection-labeler@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
