on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]
name: Ticket opened
jobs:
  assign:
    name: Add ticket to inbox
    runs-on: ubuntu-latest
    steps:
      - name: Add ticket to inbox
        uses: technote-space/create-project-card-action@v1
        with:
          PROJECT: Core development
          COLUMN: Inbox
          GITHUB_TOKEN: ${{ secrets.TRIAGE_TOKEN }}
          CHECK_ORG_PROJECT: true
